### ISSUE TITLE
Can you do a new release off 2.2.1[23]?

### ISSUE THREAD

**Issue by MysticRyuujin** [tomdess/docker-haproxy-certbot#12]
The docker hub image is currently built on 2.2.11 and there is a regression in rate limiting that was fixed in 2.2.12 (there's now a 2.2.13 as well). Which I need fixed.

https://github.com/haproxy/haproxy/issues/1196

I assume it's trivial for you to just kick off a new release but if it's a problem, let me know and I'll look for an alternative way to get it done :smile:

**Comment by MysticRyuujin** [comment]
ping

**Comment by davidzwa** [comment]
I'd advise a fork if you need it ;) 

Dockerhub is really easy to setup and push to! Dont let repo owners hold you back

**Comment by tomdess** [comment]
just issued a build on docker-hub. Anyway no new commit has been done, you can build the updated image by yourself just cloning locally the repo and issuing a docker build command
