### ISSUE TITLE
SSL Haproxy: fullchain.pem missing private key

### ISSUE THREAD

**Issue by TobiasCGoetz** [tomdess/docker-haproxy-certbot#13]
Hi,

thanks for providing this image.
I'm currently struggling to get my renewed certificate to be utilized properly.
Certbot creates the following files for me:

_`privkey.pem`  : the private key for your certificate.
`fullchain.pem`: the certificate file used in most server software.
`chain.pem`    : used for OCSP stapling in Nginx >=1.3.7.
`cert.pem`     : will break many server configurations, and should not be used
                 without reading further documentation (see link below)._

And when I now try and get haproxy to utilize the fullchain.pem for my HTTPS traffic I get the following error:

`'bind *:443' : No Private Key found in 'fullchain.pem' or 'fullchain.pem.key'.`

Is there a designated way for this image to handle this concatenation or am I supposed to handle this (externally?) e.g.:

`cat fullchain.pem privkey.pem > full.pem`

And configure my haproxy to utilize the full.pem?

Much appreciated. Thanks!

**Comment by tomdess** [comment]
the entrypoint script should take care of fullchain.pem file creation at first run, i suspect issues related to CERTS environment variable, please check logs

**Comment by TobiasCGoetz** [comment]
Thanks for taking the time. After not finding any errors at all I went back and sanity-checked some things.
I think I found the error in my haproxy configuration file:

~~bind *:443 ssl crt /etc/letsencrypt/live/my.domain/full.pem~~
bind *:443 ssl crt /etc/haproxy/certs/

**Comment by tomdess** [comment]
OK, so it was an haproxy configuration error
