### ISSUE TITLE
Unable to stat SSL from file

### ISSUE THREAD

**Issue by TobiasCGoetz** [tomdess/docker-haproxy-certbot#17]
Hi,

thanks again for your time.
I'm currently encountering the following issue with SSL certificates:

`parsing [/etc/haproxy/haproxy.cfg:36] : 'bind *:443' : unable to stat SSL certificate from file '/etc/haproxy/certs/' : No such file or directory.`

I have mounted _/etc/letsencrypt_ and _/etc/haproxy/haproxy.cfg_ as per your example. This is something that has recently appeared without any intended change from me. The insight I'm currently lacking is how the letsencrypt certs are transferred to the /etc/haproxy/certs folder within the container.

See also:
https://github.com/tomdess/docker-haproxy-certbot/blob/master/README.md?plain=1#L53
https://github.com/tomdess/docker-haproxy-certbot/blob/master/conf/haproxy.cfg#L45

Best
Tobi

**Comment by tomdess** [comment]
path $PWD/data/letsencrypt must exist before starting containers with command "docker-compose up -d" (run command in the same directory where is docker-compose.yml)

**Comment by TobiasCGoetz** [comment]
Thanks. The directory does indeed exist. I'm getting the error on two setups that were working for quite some time now.

**Comment by tomdess** [comment]
i think you are still using an old image, force a pull of the new image (docker-compose down && docker-compose pull && docker-compose up -d). It's a commn issue when you use latest/master tag

**Comment by TobiasCGoetz** [comment]
The issue persists when I pin the your container version to 2.4.19.
Maybe we could circle back to 

> The insight I'm currently lacking is how the letsencrypt certs are transferred to the /etc/haproxy/certs folder within the container.

Because the _letsencrypt_ folder seems populated with the certs folder not being created on my end.

€: Could this be related to the [CERT1/CERT2 change?](https://github.com/tomdess/docker-haproxy-certbot/blob/4961c7c7bdd0ef29c4699ed128d2decb3a784023/run/docker-compose.yml)

Thanks

**Comment by tomdess** [comment]
you right, since last change for multi-certificate support you have to change the configuration replacing CERT with CERT1, i'll try to think a fix for supporting the old configuration
