### ISSUE TITLE
docker build for arm

### ISSUE THREAD

**Issue by pablo-kabe** [tomdess/docker-haproxy-certbot#21]
It's possible make docker build for arm?

**Comment by tomdess** [comment]
hello @pablo-kabe, i've seen your patch on your fork repo: is it working? (i'll patch even my GH action file if it works)

**Comment by pablo-kabe** [comment]
hi @tomdess not, is not working, I not can launch github actions for test, finally I build image directly in my server and build well for arm, but maybe is interesting this fix
