### ISSUE TITLE
haproxy doesn't reload after cert renewal

### ISSUE THREAD

**Issue by neseih** [tomdess/docker-haproxy-certbot#25]
Hi,

supervisorctl cannot connect to the url http://localhost:9001, so after renewal, the certs are not reloaded.

Can be fixed by adding the unix_http_server section to the custom supervisord.conf
```
[supervisorctl]
# serverurl=http://localhost:9001
serverurl=unix:///tmp/supervisor.sock ; 

[unix_http_server]
file=/tmp/supervisor.sock ; 

[supervisord]
# ...
```

**Comment by tomdess** [comment]
thank you @neseih

**Comment by neseih** [comment]
Thank you @tomdess for your great work
