### ISSUE TITLE
Wildcard verification failing with CERTS with docker-compose

### ISSUE THREAD

**Issue by davidzwa** [tomdess/docker-haproxy-certbot#3]
Very nice container, worked very well except I might have a problem with a wildcard domain.

*.domain.suffix in the CERTS variable in a docker-compose results in an error that certbot cannot perform the challenge (suggesting to use DNS, which I would not prefer at all)

If I remove the wildcard, everything goes fine. Could this be a 'special character' thing? I triple checked our DNS and wildcard is definitely pointing towards our server (although we do have another subdomain pointing to another server as well).

**Comment by tomdess** [comment]
wildcard certificates must be validated by a DNS-01 challenge, the HTTP validation is not supported by ACMEv2 standard (see https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578/1)

**Comment by davidzwa** [comment]
Ah yeah when I thought a bit about it, that's also what I suspected! Thanks for getting back on it
