### ISSUE TITLE
EMAIL variable is unbound in cert-renewal-haproxy script

### ISSUE THREAD

**Issue by eliknebel** [tomdess/docker-haproxy-certbot#5]
It appears that when using supervisord, you must explicitly pass in environment variables through the configuration. This leads to an issue on cert renewal where the EMAIL variable is accessed in cert-renewal-haproxy.sh but isn't set crashing the script and failing to renew certs.

**Comment by tomdess** [comment]
it seems that even setting the environment=EMAIL="%(ENV_EMAIL)s" in supervisord config the cron process ignores it, i'm going to test the solution proposed [here](https://stackoverflow.com/questions/27771781/how-can-i-access-docker-set-environment-variables-from-a-cron-job) saving the container environment to a file in bootstrap script and reading the same file in cron with BASH_ENV=/container.env

**Comment by tomdess** [comment]
it works (fixed with tag 2.0.3)
