### ISSUE TITLE
Problem with mount

### ISSUE THREAD

**Issue by mozartatplay** [tomdess/docker-haproxy-certbot#7]
When running the following suggested command with my CERT domain

docker run --name inethi-haproxyssl -d \
    -e CERTS=inethidev.net \
    -e EMAIL=test@gmail.com \
    -v /srv/letsencrypt:/etc/letsencrypt \
    -v /srv/haproxycfg/haproxy.cfg:/etc/haproxy/haproxy.cfg \
    --network inethi-bridge \
    -p 80:80 -p 443:443 \
    tomdess/haproxy-certbot:latest

I get the follow error

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/srv/haproxycfg/haproxy.cfg\\\" to rootfs \\\"/var/lib/docker/overlay2/5a375659d70bc6c60811936fd8ecd0ed7f78f042d2369d0b049b1e4a5ddceafa/merged\\\" at \\\"/var/lib/docker/overlay2/5a375659d70bc6c60811936fd8ecd0ed7f78f042d2369d0b049b1e4a5ddceafa/merged/etc/haproxy/haproxy.cfg\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

Do I need to change something in my mount ... I noticed it created a path /srv/haproxycfg/haproxy.cfg/ where haproxy.cfg was a directory not a file

**Comment by tomdess** [comment]
you must create the file  /srv/haproxycfg/haproxy.cfg before running the "docker run" command

**Comment by mozartatplay** [comment]
Thanks Tom - silly mistake
