### ISSUE TITLE
Removed ACME?

### ISSUE THREAD

**Issue by MysticRyuujin** [tomdess/docker-haproxy-certbot#8]
Can you explain the removal of the acme file and recent changes?

I'm trying to understand how this will impact my setup, I'm worried my certs won't renew now.

I used to have (trimmed to minimize clutter):
```
global
  lua-load /etc/haproxy/acme-http01-webroot.lua

frontend http-https-in
  bind *:80
  bind *:443 ssl crt /etc/haproxy/certs/ no-sslv3 no-tls-tickets no-tlsv10 no-tlsv11
  mode http
  monitor-uri /health
  acl letsencrypt_http_acl path_beg /.well-known/acme-challenge/
  use_backend letsencrypt_http if letsencrypt_http_acl

backend letsencrypt_http
  mode http
  server letsencrypt_http_srv 127.0.0.1:8080
```

However, after updating, that lua-load threw an error, so I commented it out. Do I not need it at all?

**Comment by tomdess** [comment]
The lua stuff is totally useless now with new certbot binary and due to ACME v1 deprecation and dismissal. Please have a look  to haproxy configuration file in conf directory for the changes involved.
The renewal process still works and is carried on entirely by certbot binary.

**Comment by MysticRyuujin** [comment]
I did try to follow along but I couldn't really figure out what is going on with haproxy in the new setup. Does this mean there's no need for any haproxy forwarding to certbot?

**Comment by MysticRyuujin** [comment]
It seems like the ACME stuff was put back now? I don't get it haha

**Comment by tomdess** [comment]
yes, ACME stuff back in place :-)
